/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:17:42 IST 2016. 

0 2 Binary IMSMessageLength
2 2 Binary ReservedforIMS
4 9 Text IMS Transaction
13 6 Text Filler1 blank
19 8 Text MidName SWITCH
27 1 Text LogicalPage D
28 1 Text Gobble W
29 11 Text Filler2 blank
40 2 Binary Filler3 0
42 2 Binary Filler4 0
44 79 Text Filler5 blank
123 2 Binary Filler6 0
125 79 Text Filler7 blank
204 2 Binary Filler8 0
206 17 Text Filler9 blank
223 2 Binary Filler10 0
225 6 Text Filler11 blank
231 2 Binary Filler12 0
233 26 Text Session ID
249 12 Text Message ID
271 7 Text Filler13 blank
278 2 Binary Filler14 0
280 1 Binary SRC 1
281 1 Text Filler15 blank
282 2 Binary Filler16 0
284 20 Text Filler17 blank
*/
package com.reactiva.hazelq.protoc.dto;

import java.io.Serializable;

import com.reactiva.hazelq.protoc.Attribute;
import com.reactiva.hazelq.protoc.Format;
import com.reactiva.hazelq.protoc.Protocol;

@Protocol(name = "APPLICATIONHEADER")
public class HQDataSecHeader implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.BINARY, offset = 280, length = 1, constant = "1")
	private byte[] sRC = new byte[1];
	@Format(attribute = Attribute.TEXT, offset = 19, length = 8, constant = "SWITCH")
	private String midName = "";
	@Format(attribute = Attribute.TEXT, offset = 27, length = 1, constant = "D")
	private String logicalPage = "";
	@Format(attribute = Attribute.TEXT, offset = 28, length = 1, constant = "W")
	private String gobble = "";
	@Format(attribute = Attribute.TEXT, offset = 249, length = 22, constant = "ID")
	private String message = "";
	@Format(attribute = Attribute.BINARY, offset = 0, length = 2, constant = "")
	private byte[] iMSMessageLength = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 281, length = 1, constant = "blank")
	private String filler15 = "";
	@Format(attribute = Attribute.BINARY, offset = 278, length = 2, constant = "0")
	private byte[] filler14 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 271, length = 7, constant = "blank")
	private String filler13 = "";
	@Format(attribute = Attribute.BINARY, offset = 231, length = 2, constant = "0")
	private byte[] filler12 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 206, length = 17, constant = "blank")
	private String filler9 = "";
	@Format(attribute = Attribute.TEXT, offset = 233, length = 16, constant = "ID")
	private String session = "";
	@Format(attribute = Attribute.TEXT, offset = 284, length = 20, constant = "blank")
	private String filler17 = "";
	@Format(attribute = Attribute.BINARY, offset = 282, length = 2, constant = "0")
	private byte[] filler16 = new byte[2];
	@Format(attribute = Attribute.BINARY, offset = 123, length = 2, constant = "0")
	private byte[] filler6 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 44, length = 79, constant = "blank")
	private String filler5 = "";
	@Format(attribute = Attribute.BINARY, offset = 204, length = 2, constant = "0")
	private byte[] filler8 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 125, length = 79, constant = "blank")
	private String filler7 = "";
	@Format(attribute = Attribute.BINARY, offset = 2, length = 2, constant = "")
	private byte[] reservedforIMS = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 29, length = 11, constant = "blank")
	private String filler2 = "";
	@Format(attribute = Attribute.TEXT, offset = 13, length = 6, constant = "blank")
	private String filler1 = "";
	@Format(attribute = Attribute.BINARY, offset = 42, length = 2, constant = "0")
	private byte[] filler4 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 4, length = 9, constant = "Transaction")
	private String iMS = "";
	@Format(attribute = Attribute.BINARY, offset = 40, length = 2, constant = "0")
	private byte[] filler3 = new byte[2];
	@Format(attribute = Attribute.TEXT, offset = 225, length = 6, constant = "blank")
	private String filler11 = "";
	@Format(attribute = Attribute.BINARY, offset = 223, length = 2, constant = "0")
	private byte[] filler10 = new byte[2];

	public byte[] getSRC() {
		return sRC;
	}

	public void setSRC(byte[] sRC) {
		this.sRC = sRC;
	}

	public String getMidName() {
		return midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	public String getLogicalPage() {
		return logicalPage;
	}

	public void setLogicalPage(String logicalPage) {
		this.logicalPage = logicalPage;
	}

	public String getGobble() {
		return gobble;
	}

	public void setGobble(String gobble) {
		this.gobble = gobble;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public byte[] getIMSMessageLength() {
		return iMSMessageLength;
	}

	public void setIMSMessageLength(byte[] iMSMessageLength) {
		this.iMSMessageLength = iMSMessageLength;
	}

	public String getFiller15() {
		return filler15;
	}

	public void setFiller15(String filler15) {
		this.filler15 = filler15;
	}

	public byte[] getFiller14() {
		return filler14;
	}

	public void setFiller14(byte[] filler14) {
		this.filler14 = filler14;
	}

	public String getFiller13() {
		return filler13;
	}

	public void setFiller13(String filler13) {
		this.filler13 = filler13;
	}

	public byte[] getFiller12() {
		return filler12;
	}

	public void setFiller12(byte[] filler12) {
		this.filler12 = filler12;
	}

	public String getFiller9() {
		return filler9;
	}

	public void setFiller9(String filler9) {
		this.filler9 = filler9;
	}

	public String getSession() {
		return session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	public String getFiller17() {
		return filler17;
	}

	public void setFiller17(String filler17) {
		this.filler17 = filler17;
	}

	public byte[] getFiller16() {
		return filler16;
	}

	public void setFiller16(byte[] filler16) {
		this.filler16 = filler16;
	}

	public byte[] getFiller6() {
		return filler6;
	}

	public void setFiller6(byte[] filler6) {
		this.filler6 = filler6;
	}

	public String getFiller5() {
		return filler5;
	}

	public void setFiller5(String filler5) {
		this.filler5 = filler5;
	}

	public byte[] getFiller8() {
		return filler8;
	}

	public void setFiller8(byte[] filler8) {
		this.filler8 = filler8;
	}

	public String getFiller7() {
		return filler7;
	}

	public void setFiller7(String filler7) {
		this.filler7 = filler7;
	}

	public byte[] getReservedforIMS() {
		return reservedforIMS;
	}

	public void setReservedforIMS(byte[] reservedforIMS) {
		this.reservedforIMS = reservedforIMS;
	}

	public String getFiller2() {
		return filler2;
	}

	public void setFiller2(String filler2) {
		this.filler2 = filler2;
	}

	public String getFiller1() {
		return filler1;
	}

	public void setFiller1(String filler1) {
		this.filler1 = filler1;
	}

	public byte[] getFiller4() {
		return filler4;
	}

	public void setFiller4(byte[] filler4) {
		this.filler4 = filler4;
	}

	public String getIMS() {
		return iMS;
	}

	public void setIMS(String iMS) {
		this.iMS = iMS;
	}

	public byte[] getFiller3() {
		return filler3;
	}

	public void setFiller3(byte[] filler3) {
		this.filler3 = filler3;
	}

	public String getFiller11() {
		return filler11;
	}

	public void setFiller11(String filler11) {
		this.filler11 = filler11;
	}

	public byte[] getFiller10() {
		return filler10;
	}

	public void setFiller10(byte[] filler10) {
		this.filler10 = filler10;
	}

	public HQDataSecHeader() {
	}
}