/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 16:21:24 IST 2016. 

0 154 outheader MVSOutboundITOCHeader
154 304 appheader ApplicationHeader
*/
package com.reactiva.hazelq.protoc.dto;

import java.io.Serializable;

import com.reactiva.hazelq.protoc.Attribute;
import com.reactiva.hazelq.protoc.Format;
import com.reactiva.hazelq.protoc.Protocol;
import com.reactiva.hazelq.protoc.dto.HQDataSecHeader;
import com.reactiva.hazelq.protoc.dto.HQOutboundHeader;

@Protocol(name = "ITOCRESPONSE")
public class HQResponse implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.APPHEADER, offset = 154, length = 304, constant = "")
	private HQDataSecHeader applicationHeader = null;
	@Format(attribute = Attribute.OUTHEADER, offset = 0, length = 154, constant = "")
	private HQOutboundHeader mVSOutboundITOCHeader = null;

	public HQDataSecHeader getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(HQDataSecHeader applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public HQOutboundHeader getMVSOutboundITOCHeader() {
		return mVSOutboundITOCHeader;
	}

	public void setMVSOutboundITOCHeader(
			HQOutboundHeader mVSOutboundITOCHeader) {
		this.mVSOutboundITOCHeader = mVSOutboundITOCHeader;
	}

	public HQResponse() {
		applicationHeader = new HQDataSecHeader();
		mVSOutboundITOCHeader = new HQOutboundHeader();
	}
}