/* Generated by SMSNOW protocol CodeGen on Wed Aug 03 17:47:53 IST 2016. 

0 108 inheader MVSInboundITOCHeader
108 304 appheader ApplicationHeader
*/
package com.reactiva.hazelq.protoc.dto;

import java.io.Serializable;

import com.reactiva.hazelq.protoc.Attribute;
import com.reactiva.hazelq.protoc.Format;
import com.reactiva.hazelq.protoc.Protocol;
import com.reactiva.hazelq.protoc.dto.HQDataSecHeader;
import com.reactiva.hazelq.protoc.dto.HQInboundHeader;

@Protocol(name = "ITOCREQUEST")
public class HQRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	@Format(attribute = Attribute.APPHEADER, offset = 108, length = 304, constant = "")
	private HQDataSecHeader applicationHeader = null;
	@Format(attribute = Attribute.INHEADER, offset = 0, length = 108, constant = "")
	private HQInboundHeader mVSInboundITOCHeader = null;

	public HQDataSecHeader getApplicationHeader() {
		return applicationHeader;
	}

	public void setApplicationHeader(HQDataSecHeader applicationHeader) {
		this.applicationHeader = applicationHeader;
	}

	public HQInboundHeader getMVSInboundITOCHeader() {
		return mVSInboundITOCHeader;
	}

	public void setMVSInboundITOCHeader(HQInboundHeader mVSInboundITOCHeader) {
		this.mVSInboundITOCHeader = mVSInboundITOCHeader;
	}

	public HQRequest() {
		applicationHeader = new HQDataSecHeader();
		mVSInboundITOCHeader = new HQInboundHeader();
	}
}